# Generated by Django 4.0.3 on 2022-03-09 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Iqtisoslashgan maktab',
                'verbose_name_plural': 'Iqtisoslashgan maktablar',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Tuman')),
                ('public_schools', models.IntegerField(blank=True, verbose_name='Maktablar soni')),
                ('boarding_schools', models.ManyToManyField(blank=True, to='Bot.boardingschool', verbose_name='Iqtisoslashgan maktablar')),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID User')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='@username')),
                ('is_allowed', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Name in Telegram')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name')),
                ('is_registered', models.BooleanField(default=False, verbose_name='Is Registered')),
                ('school', models.CharField(blank=True, max_length=100, null=True, verbose_name='School')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bot.district', verbose_name='Tumani')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
    ]
