# Generated by Django 3.2.12 on 2022-03-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Maktab', 'verbose_name_plural': 'Maktablar'},
        ),
    ]
