# Generated by Django 3.2.12 on 2022-03-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0002_alter_school_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nomi'),
        ),
    ]
