# Generated by Django 3.2.12 on 2022-03-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0003_alter_district_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
    ]
