# Generated by Django 3.2.12 on 2022-03-21 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0005_alter_user_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField(unique=True, verbose_name='Variant raqami')),
                ('answers', models.CharField(max_length=255, verbose_name='Javoblar')),
                ('source', models.FileField(upload_to='tests/', verbose_name='Test')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bot.subject', verbose_name="Yo'nalish")),
            ],
        ),
    ]
