# Generated by Django 3.2.12 on 2022-03-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0006_subject_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Fan', 'verbose_name_plural': 'Fanlar'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Testlar'},
        ),
    ]
