# Generated by Django 3.2.12 on 2022-03-26 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0007_auto_20220321_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='source',
            new_name='file',
        ),
        migrations.AddField(
            model_name='test',
            name='source_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
