# Generated by Django 3.2.12 on 2022-03-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0008_auto_20220326_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='file',
            field=models.FileField(blank=True, upload_to='tests/', verbose_name='Test'),
        ),
    ]
