# Generated by Django 3.2.12 on 2022-03-27 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0010_author_book_bookcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcategory',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
    ]
